version: '3.8'

services:
  helvetiquant:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - config.env
    volumes:
      - ./backend:/app/backend
      - ./frontend_live:/app/frontend