version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helvetiquant_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: helvetiquant_redis
    ports:
      - "6379:6379"